# Generated by Django 5.1.4 on 2026-02-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paquetes', '0002_paquete_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ci',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Cédula de Identidad'),
        ),
    ]
