# Generated by Django 5.1.4 on 2026-02-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paquetes', '0003_cliente_ci'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='destino',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paquete',
            name='origen',
            field=models.CharField(default='Oficina ATL', max_length=100),
        ),
    ]
